my_aws_region = "Enter region"
my_access_key = "Enter access_key"
my_secret_key = "Enter secret_key"
my_domain_name = "Enter your Domain_name"
my_web_sub_domain_name = "Enter your web_sub_domain_name"
my_mail_sub_domain_name = "Enter your mail_sub_domain_name"
my_local_aws_private_key_path = "Paste your private_key_path"
my_key_name = "Enter your key-pair name"